"""Added missing is_deleted column in user

Revision ID: 6300233f0624
Revises: e3e84cfcf959
Create Date: 2023-09-02 01:58:17.529974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6300233f0624'
down_revision: Union[str, None] = 'e3e84cfcf959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###
